### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by ralyodio** [go-skynet/LocalAI#319]
$ curl http://localhost:8080/v1/models
curl: (56) Recv failure: Connection reset by peer

**Comment by ralyodio** [comment]
looks like it wasn't finished booting, had to wait about 60 seconds.

**Comment by developerisnow** [comment]
> looks like it wasn't finished booting, had to wait about 60 seconds.

The same error, it's not about 60sec.
Installed by `docker-compose up -d --pull always` - wait 10 min. (also tried restart)

**Comment by jcc10** [comment]
This may need to be re-opened since it would be best for there to be a interim error that gets passed until it's fully loaded. A 503 error code might be best for indicating that the server is functioning properly but has yet to fully initialize. Having a proper error message would also be really good.

I would at least make the models endpoint respond with it since it's the first point anything should check. It has caused me to restart it several times trying to figure out what I did wrong to mess up the configuration while trying to make docker-compose work with CUDA.

**Comment by SamirSaidani** [comment]
A workaround to check the server:
`watch -n 1 docker ps`

and wait that the health status changes from (health: starting) to healthy.
